spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PansionatDB
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: dbo
    show-sql: true
server:
  port: 8080